#!/bin/bash
cd $(dirname $0)

cd matrix-js-sdk
git checkout . && git pull
jsver=$(git rev-parse origin/develop)
jsver=${jsver:0:12}
cd ../matrix-react-sdk
git checkout . && git pull
reactver=$(git rev-parse origin/develop)
reactver=${reactver:0:12}
cd ..
git checkout yarn.lock
bash -c "git stash && git pull && git stash pop"
ver=$(git rev-parse origin/develop)
ver=${ver:0:12}

docker run --rm -w /data -it \
	-v $(pwd):/data \
	-v $(pwd)/.home:/home/tulir \
	-v /etc/passwd:/etc/passwd:ro \
	--env VERSION="$ver-react-$reactver-js-$jsver" \
	--env RIOT_LANGUAGES_FILE="../../webapp/i18n/languages.json" \
	--env NODE_OPTIONS="--openssl-legacy-provider" \
	node:lts-alpine \
	/bin/sh -c 'apk add --no-cache git su-exec && su-exec 1000:1000 /data/build-sh'

if [[ $? -eq 0 ]]; then
	sudo rsync --delete -tvhr webapp/ /srv/web/mau.chat/
fi
