name: Release Drafter
on:
    workflow_dispatch: {}
concurrency: ${{ github.workflow }}
jobs:
    draft:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-drafter-workflow.yml@develop
        with:
            include-changes: matrix-react-sdk
