# Gitflow merge-back master->develop
name: Merge master -> develop
on:
    workflow_dispatch:
concurrency: ${{ github.repository }}-${{ github.workflow }}
jobs:
    merge:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-gitflow.yml@develop
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
        with:
            dependencies: |
                matrix-react-sdk
                matrix-js-sdk
