name: Sync maunium fork

on:
  schedule:
    - cron: '56 16 * * *' # 16:56 UTC
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: maunium
          base: develop
          head: develop
          auto_merge: false