name: Sync labels
on:
    workflow_dispatch: {}
jobs:
    sync-labels:
        uses: element-hq/element-meta/.github/workflows/sync-labels.yml@develop
        with:
            LABELS: |
                element-hq/element-meta
                .github/labels.yml
            DELETE: true
            WET: true
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
