name: Sync vector-im fork

on:
  schedule:
    - cron: '56 8 * * *' # 8:56 UTC
  workflow_dispatch: # on button click
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.PAT }}
      - run: git remote add upstream https://github.com/vector-im/element-web
      - run: git fetch upstream
      - run: git reset --hard upstream/develop
      - run: rm -rf .github/workflows/*
      - uses: peter-evans/create-pull-request@v5
        with:
          author: GitHub <noreply@github.com>
          branch: vector-im-develop
          token: ${{ secrets.PAT }}